#!/bin/bash
#
# use "grep" to find all the occurances
#	 of following patterns in a file
#
# 	1. lines starting with M
#
#	2. Blank lines
#
#	3. lines with 2 or more a's
#
#	4. lines with 2 or more digit numbers
#
#	5. lines with patter [x,y]
#              where x,y => numbers

# setting a variable to contain filename
p_file=pattern_file

# using grep with regexp to find patterns
# usage: grep 'pattern' file-name
#
# pattern: '^abc' => lines starting with abc
echo
echo "Lines starting with \"M\": "
grep '^M' $p_file
echo

# pattern: '^$' => line begins empty, ends empty
#	blank line
echo
echo "Number of blank lines:"
grep '^$' $p_file | wc --lines
echo

# pattern: 'aa+' => lines with 2 or more a's
# extended regexp => use of -E option with grep
echo
echo "Lines containing 2 or more a's:"
grep -E 'aa+' $p_file
echo

# pattern: '[0-9][0-9]+' => 2 or more digits of numbers
echo
echo "Lines with 2 or more digits of numbers:"
grep -E '[0-9][0-9]+' $p_file
echo

# pattern: '\[[0-9],[0-9]\]' => [x,y]
#	x,y => numbers
# use of \ for using [ as a normal char
#
echo
echo "Lines with pattern [x,y]:"
grep -E '\[[0-9]+,[0-9]+\]' $p_file
echo


# end of script

